; PlatformIO Project Configuration

[env:esp32s3-devkitc-1]
platform = espressif32
board = esp32-s3-devkitc-1
framework = arduino

; Use the USB-to-UART "COM" port for both upload and serial monitor.
upload_protocol = esptool
upload_speed = 460800
upload_port = COM7

monitor_port = COM7
monitor_speed = 115200

build_flags =
    -D ARDUINO_USB_MODE=0
    -D ARDUINO_USB_CDC_ON_BOOT=0
